### ISSUE TITLE
Add GeoNode Connection Manager Dialog

### ISSUE THREAD

**Issue by ismailsunni** [kartoza/QGIS#11] opened 2017-03-23 03:03 UTC
We need a similar windows like the `Add PostGIS Table` one. The dialog will be use to create new client to geonode as well as edit and delete.
The dialog should be put under Web menu bar.

**Comment by myarjunar** [comment] 2017-03-23 12:14
Geonode connection manager dialog wireframe:
The table will contain layer description and layer service type.
![add postgis table s _046](https://cloud.githubusercontent.com/assets/11134669/24247062/b168b28e-0ffc-11e7-8eb4-7921053e2bbf.png)

New geonode connection dialog wireframe:
![create a new ms- connection_044](https://cloud.githubusercontent.com/assets/11134669/24247065/b5980f80-0ffc-11e7-807b-e2bc536d9ed4.png)
![create a new ms- connection_045](https://cloud.githubusercontent.com/assets/11134669/24247069/b7642b6e-0ffc-11e7-9885-dde2b6c9a49a.png)

**Comment by Gustry** [comment] 2017-03-23 12:28
Is it not a duplicate of #2 ?

**Closed** 2017-07-04 07:10 UTC
Labels: in progress, WBExtension
